[[redirects]]
  from = "/safebooru.org"
  to = "https://safebooru.org/index.php?page=dapi&s=post&q=index&limit=20&pid=0&json=1"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/safebooru.org/*"
  to = "https://safebooru.org/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}    
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"